### PR TITLE
Update Getting Started.txt

### PR DESCRIPTION
**Pull request by colbycocking**
Issues Resolved: 
* Incorrect version of JDK used in installation portion. 8 -> 11
* file names were incorrect. Changed documentation to reflect new file names:
*Windows: ma-start.bat -> mango.cmd
*ma.sh start -> mango-start.sh
*ma.sh stop -> mango-stop.sh
*classes file no longer exists. Changed documentation to reflect this.

Added links to mango 4 documentation pages that would provide users with more detailed information and would save them the trouble of having to locate that documentation on their own.

### CODE REVIEW

**Comment by terrypacker** [comment]
@colbycocking I suggest the following changes but please wait for @jazdw to add his review before making changes:

- [ ] Change line 9 to read `Mango requires at least Java JDK 1.8 ...` since it really does only require 1.8 but we suggest 11.  
- [ ] There is some more information about running on Windows that @jazdw can probably provide.

**Comment by colbycocking** [comment]
>     * [ ]  Change line 9 to read `Mango requires at least Java JDK 1.8 ...` since it really does only require 1.8 but we suggest 11.

I wondered if that was the case because I originally installed and got it working using 1.8 because of the original getting started.txt

**Comment by colbycocking** [comment]
@terrypacker I still don't have the ability to tick your boxes in here, but I believe this should be complete.

**Comment by terrypacker** [comment]
@colbycocking we should use RadixIot instead of Infinite Automation on this line:

```
... Infinite Automation recommends using OpenJDK 11.
```

**Comment by colbycocking** [comment]
@terrypacker fixed.

**Pull request merged**
